# Generated by Django 3.0.5 on 2020-07-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('question_type', models.CharField(choices=[('Maths', 'Math'), ('Science', 'Science'), ('English', 'English'), ('Others', 'Others')], default=1, max_length=100)),
                ('description', models.TextField()),
                ('picture', models.ImageField(blank=True, max_length=255, null=True, upload_to='pictures/')),
            ],
        ),
    ]
