# Generated by Django 3.0.5 on 2020-07-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='picture',
            field=models.ImageField(default='pctures/None/no-img.jpg', upload_to='pictures/'),
        ),
        migrations.AlterField(
            model_name='query',
            name='question_type',
            field=models.CharField(choices=[('Programming', 'Programming'), ('Math', 'Math'), ('Science', 'Science'), ('English', 'English'), ('Others', 'Others')], default=1, max_length=100),
        ),
    ]
